public class IF_KnoxCalendarCreation {
	private static final String INTERFACE_ID = 'IF-191';
    private static final String APEX_CLASS   = 'IF_KnoxCalendarCreation';
    private static final String METHOD_NAME  = 'SendTXPManpowerInfo';
    private static String guId = IF_Util.generateGuid();
    private static Integer errorCount = 0;
    public static Map<String,Object> resMap = new Map<String,Object>();
    Public Static void  doCalloutCreatemySalesKnoxCalendar(){
    	    
    }
}