/**
 * @description       : 
 * @author            : Junghwa.Kim@dkbmc.com
 * @group             : 
 * @last modified on  : 11-25-2020
 * @last modified by  : Junghwa.Kim@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                  Modification
 * 1.0   11-25-2020   Junghwa.Kim@dkbmc.com   Initial Version
**/
@isTest
public class SalesLeadPathController_Test {
    @isTest
    public static void SalesLeadPathController() {
        SalesLeadPathController.getStageVal('//');
    }
}