/**
 * @description       : Test class of showLogisticOpptyCountCtrl 
 * @author            : d.ashish@samsung.com
 * @group             : 
 * @last modified on  : 2023-06-07
 * @last modified by  : d.ashish@samsung.com
 * Modifications Log 
 * Ver   Date         Author                   Modification
 * 1.0   2023-06-07   d.ashish@samsung.com   Initial Version
**/
@isTest
public class showLogisticOpptyCountCtrl_Test {
@isTest
    public static void testshowLogisticOppty(){
        showLogisticOpptyCountCtrl.getCount();
        showLogisticOpptyCountCtrl.getUserDetail();
    }
}