/**
 * @author            : hyunhak.roh@dkbmc.com
 * @group             : 
 * @description       : 
 * @last modified on  : 2022-06-16
 * @last modified by  : hyunhak.roh@dkbmc.com
 * Modifications Log 
 * Ver   Date         Author                    Modification
 * 1.0   2022-06-16   hyunhak.roh@dkbmc.com   Initial Version
**/
public class TriggerControl {
    
    // 2022-06-16, hyunhak.roh@dkbmc.com, 사업리드 Converted BO가 삭제 시 해당 사업리드 단계를 되돌리는 로직 추가
	public static Boolean isOpptyDeleteToSalesLead = false;
}